### ISSUE TITLE
What's wrong with this one?

### ISSUE THREAD

**Issue by jenstornell** [pedroborges/kirby-google-analytics#1]
What's wrong with this one?
https://github.com/jenstornell/ga

**Comment by pedroborges** [comment]
Hey @jenstornell! There's nothing wrong with your plugin.

I'm taking repetitive solutions I use on most project and moving them into small plugins so I can easily install them on new project and update them one existing ones. You can expect more of that in the future.

Regarding Google Analytics, I also have a few more advanced features in mind. That's why I prefer to have my own.

**Comment by jenstornell** [comment]
>I'm taking repetitive solutions I use on most project and moving them into small plugins

Sounds kind of like me then. :)

>I also have a few more advanced features in mind

Is that by duplicating features that I already have in my plugin or is it other features? I hope it's other features, else I don't really see the point.

**Comment by pedroborges** [comment]
> Is that by duplicating features that I already have in my plugin or is it other features?

From what I see that your plugin does, what I have in mind is different.

**Comment by jenstornell** [comment]
You are not exactly like an open book. ;)

The only thing my plugin does is show the script in different cases, when a user is not logged in and not on a localhost environment and if the IP is not in the blacklist. It will however show it if debug is true.

You can get inspired by these things if you want but I hope you also bring something new to the table. :)

But it was a while ago I wrote my plugin and I have a few changes in mind. I will use registry to set the snippet (registry did not exist back then). I will also use a snippet similar to yours in the footer with the possibility to send the UA-code directly to that snippet with an argument. I will also change the repo name to kirby-ga instead of just ga. I will however never present stats in the Panel so if that's what's on your mind you will make a different plugin than me.

**Comment by pedroborges** [comment]
> I will however never present stats in the Panel so if that's what's on your mind you will make a different plugin than me.

This is one of the things, since most clients wouldn't understand Google Analytics dashboard. I'd like to try doing something simple.

**Comment by jenstornell** [comment]
As far as I can see there are no plugin that does which is great. Good luck!

*Be aware that Google APIs in general can be a bit tricky*

**Comment by pedroborges** [comment]
I haven't even looked at the API, I'm pretty sure it will be very time consuming so I'm not trying that anytime soon.
